### ISSUE TITLE
Error when launching app

### ISSUE THREAD

**Issue by WinOpsEngineer** [pseymour/MakeMeAdmin#85]
I am getting this error when launching the app . Is there a pre-req that's missing?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.String[]'.
   at SinclairCC.MakeMeAdmin.Settings.GetMultiString(String keyPath, String subkeyName, String valueName)
   at SinclairCC.MakeMeAdmin.Settings.get_LocalAllowedEntities()
   at SinclairCC.MakeMeAdmin.SubmitRequestForm.ButtonStateWorkCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

**Comment by pseymour** [comment]
It looks like you have the "Allowed Entities" registry value stored as a REG_SZ (a single-valued string). Make Me Admin expects a multi-valued string (REG_MULTI_SZ). 

https://github.com/pseymour/MakeMeAdmin/wiki/Registry-Settings

**Comment by WinOpsEngineer** [comment]
Thank you!! That fixed it.

**Comment by WinOpsEngineer** [comment]
to add multiple entries to the regkey directly do you add commas? like domain\user1,domain\user2

**Comment by pseymour** [comment]
Just put each one on a new line.

**Comment by WinOpsEngineer** [comment]
great and awesome job - Thanks!!
