### ISSUE TITLE
Program Error

### ISSUE THREAD

**Issue by gtao725** [pseymour/MakeMeAdmin#95]
Hello Community,

Just wondering if anyone has encountered this weird issue I am experiencing with MakeMeAdmin 2.3.0. I have used the program since a year ago on my Azure AD Joined machine without any issues until recently. Now everytime I launch the app, it throws the below errors, however, admin rights are granted. But, the rights will no longer time out automatically after default 10 min, and the MakeMeAdminUI seems to never light up Remove Admin Rights button anymore. The only way I can remove the rights is to manually remove myself from the Administrators group. I have tried the precompiled 2.3.0 binaries as well as the master and issue-16 branch builds as well, removing/reinstalling, remove user.xml and nothing is working. Would anyone know what is causing this weird phenomenon?

![image](https://github.com/pseymour/MakeMeAdmin/assets/35093669/1b1761b6-530d-4a02-8f8f-8e2f81efd790)
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SinclairCC.MakeMeAdmin.LocalAdministratorGroup.IsMemberOfAdministratorsDirectly(WindowsIdentity userIdentity)
   at SinclairCC.MakeMeAdmin.LocalAdministratorGroup.IsMemberOfAdministrators(WindowsIdentity userIdentity)
   at SinclairCC.MakeMeAdmin.SubmitRequestForm.UpdateUserAdministratorStatus()
   at SinclairCC.MakeMeAdmin.SubmitRequestForm.addUserBackgroundWorker_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MakeMeAdminUI
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/MakeMeAdminUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9093.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9139.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
CrowdStrike.Sensor.ScriptControl
    Assembly Version: 6.52.16606.0
    Win32 Version: 6.52.16606.0
    CodeBase: file:///C:/windows/System32/CrowdStrike.Sensor.ScriptControl16606.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UserList
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/UserList.DLL
----------------------------------------
System.DirectoryServices.AccountManagement
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices.AccountManagement/v4.0_4.0.0.0__b77a5c561934e089/System.DirectoryServices.AccountManagement.dll
----------------------------------------
LsaLogonSessions
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/LsaLogonSessions.DLL
----------------------------------------
Logging
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/Logging.DLL
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
Settings
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/Settings.DLL
----------------------------------------
Shared
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/Shared.DLL
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
ProcessCommunication
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Program%20Files/Make%20Me%20Admin/ProcessCommunication.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by goofie45** [comment]
Hello,
Error also with version 2.3.81, which .net version is required?
Thanks

************** Texte de l'exception **************
System.InvalidCastException: Impossible d'effectuer un cast d'un objet de type 'System.String' en type 'System.String[]'.
   à SinclairCC.MakeMeAdmin.Settings.GetMultiString(String keyPath, String subkeyName, String valueName)
   à SinclairCC.MakeMeAdmin.Settings.get_LocalAllowedEntities()
   à SinclairCC.MakeMeAdmin.SubmitRequestForm.ButtonStateWorkCompleted(Object sender, RunWorkerCompletedEventArgs e)
   à System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)


************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MakeMeAdminUI
    Version de l'assembly : 2.3.81.0
    Version Win32 : 2.3.81.0
    CodeBase : file:///C:/Program%20Files/Make%20Me%20Admin/MakeMeAdminUI.exe
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9181.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9206.0 built by: NET481REL1LAST_B
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9200.0 built by: NET481REL1LAST_C
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MakeMeAdminUI.resources
    Version de l'assembly : 2.3.81.0
    Version Win32 : 2.3.81.0
    CodeBase : file:///C:/Program%20Files/Make%20Me%20Admin/fr/MakeMeAdminUI.resources.DLL
----------------------------------------
ProcessCommunication
    Version de l'assembly : 2.3.81.0
    Version Win32 : 2.3.81.0
    CodeBase : file:///C:/Program%20Files/Make%20Me%20Admin/ProcessCommunication.DLL
----------------------------------------
LsaLogonSessions
    Version de l'assembly : 2.3.81.0
    Version Win32 : 2.3.81.0
    CodeBase : file:///C:/Program%20Files/Make%20Me%20Admin/LsaLogonSessions.DLL
----------------------------------------
Enumerations
    Version de l'assembly : 2.3.81.0
    Version Win32 : 2.3.81.0
    CodeBase : file:///C:/Program%20Files/Make%20Me%20Admin/Enumerations.DLL
----------------------------------------
Settings
    Version de l'assembly : 2.3.81.0
    Version Win32 : 2.3.81.0
    CodeBase : file:///C:/Program%20Files/Make%20Me%20Admin/Settings.DLL
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.8.9032.0 built by: NET481REL1
    CodeBase : file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

**Comment by pseymour** [comment]
The code that's in master branch now requires .NET 4.8.

**Comment by goofie45** [comment]
Thank you for this feedback, currently on my workstation, version 4.8.1, would you have a clue?

**Comment by pseymour** [comment]
It looks like your Allowed Entities registry value is a REG_SZ value.

**Comment by goofie45** [comment]
that's fine, thank you very much
